"""
Plan.md Generator Skill for AI Employee - Silver Tier

This module creates structured Plan.md files for tasks in the Needs_Action folder.
Plans break down complex tasks into actionable steps with checkboxes.
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional


class PlanGenerator:
    """
    Generates structured Plan.md files for tasks.
    """
    
    def __init__(self, vault_path: str):
        """
        Initialize the plan generator.
        
        Args:
            vault_path: Path to the Obsidian vault
        """
        self.vault_path = Path(vault_path)
        self.plans_folder = self.vault_path / 'Plans'
        self.plans_folder.mkdir(parents=True, exist_ok=True)
    
    def create_plan(
        self,
        task_name: str,
        objective: str,
        steps: List[Dict[str, Any]],
        metadata: Optional[Dict[str, Any]] = None,
        source_file: Optional[str] = None
    ) -> Path:
        """
        Create a new Plan.md file.
        
        Args:
            task_name: Name of the task
            objective: Overall objective description
            steps: List of step dictionaries with description and action_type
            metadata: Additional metadata
            source_file: Original file that triggered this plan
            
        Returns:
            Path to the created plan file
        """
        # Generate unique ID
        plan_id = f"PLAN_{task_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        # Create plan content
        content = self._create_plan_content(
            plan_id=plan_id,
            task_name=task_name,
            objective=objective,
            steps=steps,
            metadata=metadata,
            source_file=source_file
        )
        
        # Write file
        filename = f'{plan_id}.md'
        filepath = self.plans_folder / filename
        filepath.write_text(content)
        
        return filepath
    
    def _create_plan_content(
        self,
        plan_id: str,
        task_name: str,
        objective: str,
        steps: List[Dict[str, Any]],
        metadata: Optional[Dict[str, Any]],
        source_file: Optional[str]
    ) -> str:
        """Create markdown content for the plan."""
        
        # Build steps markdown
        steps_md = []
        for i, step in enumerate(steps, 1):
            checkbox = step.get('done', False)
            checked = '[x]' if checkbox else '[ ]'
            description = step.get('description', f'Step {i}')
            action_type = step.get('action_type', '')
            notes = step.get('notes', '')
            
            step_md = f'- {checked} **Step {i}**: {description}"
            if action_type:
                step_md += f' *(Type: {action_type})*'
            step_md += '\n'
            if notes:
                step_md += f'  - Notes: {notes}\n'
            
            steps_md.append(step_md)
        
        # Build metadata section
        metadata_md = ''
        if metadata:
            metadata_md = f'''
## Metadata
```json
{json.dumps(metadata, indent=2, default=str)}
```
'''
        
        # Source file reference
        source_md = ''
        if source_file:
            source_md = f'''
## Source
- **From**: `{source_file}`
'''
        
        content = f'''---
type: plan
id: {plan_id}
task: {task_name}
created: {datetime.now().isoformat()}
status: in_progress
completion_percentage: 0
---

# Plan: {task_name}

## Objective
{objective}

## Created
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Status
🔄 In Progress

{source_md}
## Steps

{"".join(steps_md)}

## Progress
- Total Steps: {len(steps)}
- Completed: 0
- Remaining: {len(steps)}

## Notes
*Add any additional notes, observations, or blockers here*

---

## Execution Log

| Timestamp | Step | Action | Result |
|-----------|------|--------|--------|
{self._generate_log_table()}

---
*Generated by Plan Generator v0.1 (Silver Tier)*
'''
        
        return content
    
    def _generate_log_table(self) -> str:
        """Generate empty execution log table rows."""
        rows = []
        for i in range(5):
            rows.append(f'| - | {i+1} | - | - |')
        return '\n'.join(rows)
    
    def update_plan(
        self,
        plan_path: Path,
        step_number: int,
        done: bool = True,
        result: Optional[str] = None
    ) -> bool:
        """
        Update a plan file with step completion.
        
        Args:
            plan_path: Path to the plan file
            step_number: Step number to update
            done: Whether step is complete
            result: Result of the step
            
        Returns:
            True if update successful
        """
        if not plan_path.exists():
            return False
        
        content = plan_path.read_text()
        
        # Update checkbox
        old_checkbox = f'- [ ] **Step {step_number}'
        new_checkbox = f'- [x] **Step {step_number}'
        content = content.replace(old_checkbox, new_checkbox)
        
        # Add to execution log
        if result:
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
            log_entry = f'| {timestamp} | {step_number} | Executed | {result[:50]}... |'
            content = content.replace(self._generate_log_table(), 
                                      f'| {timestamp} | {step_number} | Executed | {result[:50]}... |\n' + self._generate_log_table())
        
        plan_path.write_text(content)
        return True
    
    def create_plan_from_action_file(self, action_file: Path) -> Path:
        """
        Create a plan based on an action file's content.
        
        Args:
            action_file: Path to the action file
            
        Returns:
            Path to the created plan file
        """
        if not action_file.exists():
            raise FileNotFoundError(f'Action file not found: {action_file}')
        
        content = action_file.read_text()
        
        # Parse frontmatter
        frontmatter = self._parse_frontmatter(content)
        
        # Determine task type and generate steps
        task_type = frontmatter.get('type', 'general')
        task_name = action_file.stem
        
        # Generate steps based on type
        if task_type == 'email':
            steps = self._generate_email_steps(content, frontmatter)
            objective = f'Process email from {frontmatter.get("from", "unknown sender")}'
        elif task_type == 'whatsapp':
            steps = self._generate_whatsapp_steps(content, frontmatter)
            objective = f'Process WhatsApp message from {frontmatter.get("from", "unknown sender")}'
        elif task_type == 'file_drop':
            steps = self._generate_file_steps(content, frontmatter)
            objective = f'Process file: {frontmatter.get("original_name", "unknown file")}'
        elif task_type == 'linkedin_post':
            steps = self._generate_linkedin_steps(content, frontmatter)
            objective = 'Create and post LinkedIn update'
        else:
            steps = self._generate_generic_steps(content)
            objective = f'Process: {task_name}'
        
        return self.create_plan(
            task_name=task_name,
            objective=objective,
            steps=steps,
            metadata={'source_type': task_type, **frontmatter},
            source_file=str(action_file)
        )
    
    def _parse_frontmatter(self, content: str) -> Dict[str, str]:
        """Parse YAML frontmatter from markdown."""
        import re
        
        match = re.search(r'^---\s*\n(.*?)\n---\s*$', content, re.DOTALL)
        if not match:
            return {}
        
        frontmatter = match.group(1)
        data = {}
        
        for line in frontmatter.split('\n'):
            if ':' in line:
                key, value = line.split(':', 1)
                data[key.strip()] = value.strip()
        
        return data
    
    def _generate_email_steps(self, content: str, frontmatter: Dict) -> List[Dict]:
        """Generate steps for email processing."""
        is_known = frontmatter.get('is_known_contact', 'false').lower() == 'true'
        
        steps = [
            {'description': 'Read and understand email content', 'action_type': 'read'},
            {'description': 'Determine if response is needed', 'action_type': 'analyze'},
        ]
        
        if not is_known:
            steps.append({'description': 'Create approval request for new contact', 'action_type': 'approval'})
        
        steps.extend([
            {'description': 'Draft response', 'action_type': 'write'},
            {'description': 'Review draft for accuracy and tone', 'action_type': 'review'},
            {'description': 'Send email via Email MCP', 'action_type': 'send_email'},
            {'description': 'Mark email as read in Gmail', 'action_type': 'gmail_api'},
            {'description': 'Move to Done folder', 'action_type': 'file_op'},
        ])
        
        return steps
    
    def _generate_whatsapp_steps(self, content: str, frontmatter: Dict) -> List[Dict]:
        """Generate steps for WhatsApp message processing."""
        return [
            {'description': 'Read and understand message', 'action_type': 'read'},
            {'description': 'Determine appropriate response', 'action_type': 'analyze'},
            {'description': 'Draft reply', 'action_type': 'write'},
            {'description': 'Create approval request (required for WhatsApp)', 'action_type': 'approval'},
            {'description': 'Wait for human approval', 'action_type': 'wait'},
            {'description': 'Send reply via WhatsApp', 'action_type': 'send_whatsapp'},
            {'description': 'Move to Done folder', 'action_type': 'file_op'},
        ]
    
    def _generate_file_steps(self, content: str, frontmatter: Dict) -> List[Dict]:
        """Generate steps for file drop processing."""
        return [
            {'description': 'Read file contents', 'action_type': 'read'},
            {'description': 'Determine file type and purpose', 'action_type': 'analyze'},
            {'description': 'Identify required action', 'action_type': 'plan'},
            {'description': 'Execute required action', 'action_type': 'execute'},
            {'description': 'Archive or move file', 'action_type': 'file_op'},
            {'description': 'Move to Done folder', 'action_type': 'file_op'},
        ]
    
    def _generate_linkedin_steps(self, content: str, frontmatter: Dict) -> List[Dict]:
        """Generate steps for LinkedIn post processing."""
        return [
            {'description': 'Review post content', 'action_type': 'read'},
            {'description': 'Check for appropriate tone and content', 'action_type': 'review'},
            {'description': 'Create approval request', 'action_type': 'approval'},
            {'description': 'Wait for human approval', 'action_type': 'wait'},
            {'description': 'Post to LinkedIn', 'action_type': 'linkedin_post'},
            {'description': 'Log post for tracking', 'action_type': 'log'},
            {'description': 'Move to Done folder', 'action_type': 'file_op'},
        ]
    
    def _generate_generic_steps(self, content: str) -> List[Dict]:
        """Generate generic steps for unknown task types."""
        return [
            {'description': 'Read and understand task', 'action_type': 'read'},
            {'description': 'Identify required actions', 'action_type': 'analyze'},
            {'description': 'Execute actions', 'action_type': 'execute'},
            {'description': 'Verify completion', 'action_type': 'verify'},
            {'description': 'Move to Done folder', 'action_type': 'file_op'},
        ]


# Main entry point
if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser(description='Plan Generator')
    parser.add_argument('--vault', type=str, default='../AI_Employee_Vault',
                       help='Path to Obsidian vault')
    parser.add_argument('--action-file', type=str, help='Action file to create plan from')
    parser.add_argument('--demo', action='store_true', help='Run demo plan creation')
    
    args = parser.parse_args()
    
    script_dir = Path(__file__).parent.absolute()
    vault_path = Path(args.vault)
    
    if not vault_path.is_absolute():
        vault_path = script_dir / vault_path
    
    generator = PlanGenerator(str(vault_path))
    
    if args.demo:
        # Create demo plan
        plan_path = generator.create_plan(
            task_name='Demo Task',
            objective='Demonstrate plan generation capability',
            steps=[
                {'description': 'Initialize system', 'action_type': 'setup'},
                {'description': 'Run tests', 'action_type': 'test'},
                {'description': 'Generate report', 'action_type': 'report'},
                {'description': 'Clean up', 'action_type': 'cleanup'},
            ],
            metadata={'demo': True}
        )
        print(f'Demo plan created: {plan_path}')
    
    elif args.action_file:
        action_file = Path(args.action_file)
        if not action_file.is_absolute():
            action_file = script_dir / action_file
        
        plan_path = generator.create_plan_from_action_file(action_file)
        print(f'Plan created: {plan_path}')
    
    else:
        print('Use --demo to create a demo plan or --action-file to create plan from action file')
